version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo_todo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  backend:
    build: .
    container_name: express_todo
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - .:/app

volumes:
  mongo_data:
